### ISSUE TITLE
Port number 1 state is Down

### ISSUE THREAD

**Issue by zkzhu0110** [intel/sriov-network-device-plugin#269]
## What issue would you like to bring attention to?

I tried to create 4 VFs for Mellanox IB interface, but after installation, port state of these VFS were **down**.

This picture as follows shows states of IB interface :

![image](https://user-images.githubusercontent.com/40782501/93078232-bb9af280-f6bc-11ea-88b1-f83290084837.png)

## What is the impact of this issue?

Some commands such as ib_send_bw, ib_write_bw cannot be used, affecting tests on RDMA. So I hope port state of VFs are all active.

## Do you have a proposed response or remediation for the issue?

No, we have tried almost one day but failed. So that is why we come here for help. Thank you!

**Comment by zshi-redhat** [comment]
> ## What issue would you like to bring attention to?
> 
> I tried to create 4 VFs for Mellanox IB interface, but after installation, port state of these VFS were **down**.
> 
> This picture as follows shows states of IB interface :
> 
> Some commands such as ib_send_bw, ib_write_bw cannot be used, affecting tests on RDMA. So I hope port state of VFs are all active.
> ## Do you have a proposed response or remediation for the issue?
> 
> No, we have tried almost one day but failed. So that is why we come here for help. Thank you!

@zkzhu0110 do you have subnet manager that supports SR-IOV running somewhere in the same network?

**Comment by adrianchiris** [comment]
You require to have an active subnet manager that supports virtualization.

you can use: opensm packaged within [MLNX_OFED driver package](https://www.mellanox.com/products/infiniband-drivers/linux/mlnx_ofed) or [UFM](https://www.mellanox.com/products/ufm)

**Comment by adrianchiris** [comment]
You need to have valid GUIDs assigned to the VFs as well for link to be up.

to configure port node GUID of VF you should do it through ip link commands.
(each VF with unique value)

`ip link set <PF ipoib netdev> vf <vf idx> port_guid <GUID> node_guid <GUID>`
for VF, port and node GUID should be set to the same value.

Then unbind/bind VF from/to driver to apply the change.
On a side-note, This issue is not really related to sriov-network-device-plugin project.

[ib-sriov-cni](https://github.com/Mellanox/ib-sriov-cni) together with [ib-kubernetes](https://github.com/Mellanox/ib-kubernetes) should be used to set up the networking aspects of Infiniband VFs in pods.


ib-kubernetes can be used with `noop` SM plugin if the subnet manager is managed out of band.
it would then be used for GUID address allocation.

**Comment by zkzhu0110** [comment]
Thank you very much, currently we have solved the problem.​ We need to unbind and rebind VFs, and also need to make sure that opemd is active. 

Reference: https://community.mellanox.com/s/article/howto-configure-sr-iov-for-connect-ib-connectx-4-with-kvm--infiniband-x
