### ISSUE TITLE
Need error message when pcidp/config.json is invlid

### ISSUE THREAD

**Issue by PatrickKutch** [intel/sriov-network-device-plugin#79]
I accidentally erased the opening '{' in my config file while editing for a given platform.  A simple 'cat' of the file (which I must have done 30 times and I easily overlooked the missing bracket.

Multus logging didn't have any error messages about invalid file, looked fine.  A simple log message about the config.json being invalid may save somebody else the frustration of 6 hours looking for a dumb mistake :-)

**Comment by ahalim-intel** [comment]
Hi @PatrickKutch,
Thanks for logging the this issue. Any invalid config issues in pcidp/config.json are caught and reported by sriov device plugin.

This error can be seen in it's log as shown below if logging is enabled:

```
$ ./build/sriovdp -logtostderr

I0410 10:01:50.416344   28198 main.go:44] resource manager reading configs
E0410 10:01:50.416400   28198 main.go:46] error getting resources from file error unmarshalling raw bytes invalid character ':' after top-level value
``` 

If you are running the device plugin as daemonset using the example sriovdp-daemonset.yaml ìmages`  then you can view this  log from kubectl as shown below:

```
$ kubectl -n kube-system logs -f kube-sriov-device-plugin-amd64-q47bl 
```
These logs cannot be propagated in Multus because this isn't a CNI plugin.

**Comment by killianmuldoon** [comment]
Closing as stale
